name: test
run-name: Test ${{ inputs.working-directory }} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
  push:

env:
  UV_VERSION: "0.1.0"
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python and uv
        uses: "./.github/actions/uv_setup"
        with:
          python-version: ${{ matrix.python-version }}
          uv-version: ${{ env.UV_VERSION }}
          working-directory: ${{ inputs.working-directory }}
          cache-key: test
      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: |
          make test
